version: '3.1'

services:

  db:
    image: mariadb:10.6
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: U4W44MB5Ri
      MARIADB_DATABASE: database
      MARIADB_USER: user
      MARIADB_PASSWORD: RmPB9l5UY8

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1